// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Opea.GestaoBiblioteca.Infrastructure.Context;

#nullable disable

namespace Opea.GestaoBiblioteca.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250906230206_AdicionarSeedsEmprestimo")]
    partial class AdicionarSeedsEmprestimo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Opea.GestaoBiblioteca.Domain.Entities.Emprestimo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataDevolucao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataEmprestimo")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LivroId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("StatusEmprestimo")
                        .HasColumnType("INT");

                    b.HasKey("Id");

                    b.HasIndex("LivroId");

                    b.ToTable("Emprestimo", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            DataCriacao = new DateTime(2025, 9, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataEmprestimo = new DateTime(2025, 9, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            LivroId = new Guid("00000000-0000-0000-0000-000000000001"),
                            StatusEmprestimo = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            DataCriacao = new DateTime(2025, 9, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataDevolucao = new DateTime(2025, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataEmprestimo = new DateTime(2025, 9, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            LivroId = new Guid("00000000-0000-0000-0000-000000000002"),
                            StatusEmprestimo = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            DataCriacao = new DateTime(2025, 9, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataEmprestimo = new DateTime(2025, 9, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            LivroId = new Guid("00000000-0000-0000-0000-000000000003"),
                            StatusEmprestimo = 0
                        });
                });

            modelBuilder.Entity("Opea.GestaoBiblioteca.Domain.Entities.Livro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AnoPublicacao")
                        .HasColumnType("INT");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("VARCHAR(254)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("QuantidadeDisponivel")
                        .HasColumnType("INT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("VARCHAR(254)");

                    b.HasKey("Id");

                    b.ToTable("Livro", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            AnoPublicacao = 1954,
                            Autor = "J.R.R. Tolkien",
                            DataCriacao = new DateTime(2025, 9, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            QuantidadeDisponivel = 5,
                            Titulo = "O Senhor dos Anéis"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            AnoPublicacao = 1949,
                            Autor = "George Orwell",
                            DataCriacao = new DateTime(2025, 9, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            QuantidadeDisponivel = 3,
                            Titulo = "1984"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            AnoPublicacao = 1899,
                            Autor = "Machado de Assis",
                            DataCriacao = new DateTime(2025, 9, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            QuantidadeDisponivel = 2,
                            Titulo = "Dom Casmurro"
                        });
                });

            modelBuilder.Entity("Opea.GestaoBiblioteca.Domain.Entities.Emprestimo", b =>
                {
                    b.HasOne("Opea.GestaoBiblioteca.Domain.Entities.Livro", "Livro")
                        .WithMany("Emprestimos")
                        .HasForeignKey("LivroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Livro");
                });

            modelBuilder.Entity("Opea.GestaoBiblioteca.Domain.Entities.Livro", b =>
                {
                    b.Navigation("Emprestimos");
                });
#pragma warning restore 612, 618
        }
    }
}
